### ISSUE TITLE
Testing mirror

### ISSUE THREAD

**Issue by cdeadmin** [open-power-host-os/mirror-test#2]
<cde:info> Mirrored with LTC bug #147848 </cde:info>

**Comment by cdeadmin** [comment]
------- Comment From rmatos@br.ibm.com 2017-07-07 13:15:51 EDT-------
== Problem Description ==

== `uname -a` output ==

== Steps to recreate this bug ==

== Is this a regression from a previous kernel?  If so, which kernel? ==

== Attach the output of `sosreport` to this bug ==

**Comment by ravanelli** [comment]
Testing mirror comment

**Comment by okc-ok** [comment]
![stopwatch](https://user-images.githubusercontent.com/29638050/28179217-ddbd4670-67c6-11e7-8f5c-2231439f0334.JPG)

Test of embedding an image within the GitHub issue.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-19 21:15:32 EDT-------
Testing the NEEDINFO status.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-19 21:20:56 EDT-------
Test again ... minor change to the code.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-19 21:24:36 EDT-------
... and test again!

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-19 21:29:09 EDT-------
Adjust the format of the label which we are attempting to set into the issue.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-19 21:31:03 EDT-------
Confirm whether the label is removed when the bug leaves NEEDINFO status.

**Comment by okc-ok** [comment]
Nope ... removal of the single issue label will need more work. Test when there are additional labels already on the issue.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-19 21:35:01 EDT-------
Reprocess bug in the OPEN status.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-19 21:53:26 EDT-------
Restructure the issue modify action class and test again.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 09:32:34 EDT-------
New day, new tests for new code! Setting status = NEEDINFO

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 09:36:40 EDT-------
Enable new action in the GitHub mappings.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 09:38:13 EDT-------
Can I force the need_info label to be added?

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 09:44:31 EDT-------
Another code change to help normalize labels for comparison

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 09:46:39 EDT-------
Confirm whether the labels persist even after adding a new label to the bug.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 09:50:06 EDT-------
Reapply the 'mirror' label on the bug to see what happens ...

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 09:54:26 EDT-------
Leaving NEEDINFO status ... moving to OPEN

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 10:01:10 EDT-------
Return to status = NEEDINFO for more testing

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 10:03:10 EDT-------
Remove the 'question' label from the bug

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 10:05:35 EDT-------
Arrgh ... too many permutations! See if we can remove the need_info label via status change.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 10:07:52 EDT-------
Check on FIXEDAWAITINGTEST status

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 10:12:25 EDT-------
Fix up the code which adds labels and retest.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 10:14:05 EDT-------
Next status = TESTED

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 10:15:05 EDT-------
Run the status to CLOSED ... the 'verify' label should be removed.

------- Comment From carndt@us.ibm.com 2017-07-20 10:16:14 EDT-------
whew ... finally at CLOSED!

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 16:45:37 EDT-------
Test setting the bug severity = block

**Comment by okc-ok** [comment]
HOT label was received! Allow it to cool off now.

**Comment by cdeadmin** [comment]
------- Comment From carndt@us.ibm.com 2017-07-20 16:48:37 EDT-------
Slight cooling to 'ship issue' is permitted.
